### ISSUE TITLE
Link para o próximo e o anterior no fim da página

### ISSUE THREAD

**Issue by lipemorais** [loopinfinito/setup#46]
Quando eu termino de ler um setup quero ir para o próximo e tenho que voltar lá em cima para clicar nas setinhas. Gostaria de contribuir para o projeto e fazer isso eu mesmo mas não encontrei uma forma fácil de contribuir.

**Comment by almirfilho** [comment]
Posso fechar essa issue @lipemorais?

**Comment by lipemorais** [comment]
Pode sim.
