### ISSUE TITLE
Bug no mouse over/out na listagem dos convidados da home

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/setup#50]
Na branch refactor, o [script](https://github.com/loopinfinito/setup/tree/refactor/src/scripts) que detecta os movimentos do mouse na lista dos convidados da home está bugado.

Não importa por onde o mouse entre ou saia, pois o nome do convidado sempre aparece e desaparece pelo lado direito. Verifiquei que o método `getMouseEnterDirection` sempre retorna `1`, que corresponde à posição `right` no código, mas consegui descobrir a causa do problema. Na branch `master` está tudo ok, e a diferença entre os scripts das duas branches é apenas que removi muito lixo na `refactor`, e não modifiquei em nada o antigo script que já fazia essa detecção do mouse.

Podes dar uma olhada nisso, @caiogondim?

**Comment by caiogondim** [comment]
Prefiro retirar essa opção, pois não dá pra portar ela pra mobile.
Que acha de pensarmos em um design pra mobile e deixar esse mesmo design pra desktop?

**Comment by almirfilho** [comment]
Subi pra [staging](http://staging.setup.loopinfinito.com.br). Dá uma olhada como ficou o mobile lá e me fala o que tu acha.
Eu particularmente gosto dessa firula na home (desktop) e não vejo problema se ficar diferente do mobile, não acho que fica inconsistente saca. Mas visualiza ai e me fala. Ficou lindão S2:

**Comment by caiogondim** [comment]
O que não gosto é de não ter o nome do cara no mobile, saca?
Só a foto não diz nada pra maioria das pessoas.

Prefiro ter o nome sempre visível.

O que tu acha?

2015-07-14 14:58 GMT+02:00 Almir Filho <notifications@github.com>:

**Comment by almirfilho** [comment]
Exatamente, por isso que to falando pra você olhar em staging. Veja como está lá ;)

**Comment by caiogondim** [comment]
Investigando.

**Comment by caiogondim** [comment]
Não é preguiça de debugar. 
Mas to começando a achar essa feature um pouco ruim.

Não seria melhor termos um layout como em mobile, com o nome sempre visível, inclusive com empresa do entrevistado?
No scroll o comportamento dessa feature tá bem zuada também quando o mouse está em cima do container dos entrevistados.

**Comment by almirfilho** [comment]
Beleza, vou fazer uns experimentos sobre como ficaria no desktop, então =)
